language: java
dist: xenial
sudo: required

jdk:
- openjdk11

install: true

cache:
  directories:
  - "$HOME/.m2"
before_install:
- cp toolchains.xml ~/.m2/toolchains.xml
script: 
 - mvn clean verify
before_deploy:
  - mvn package -Dmaven.test.skip=true
deploy:
- provider: bintray
  file: releng/release.json
  on:
   repo: enterpriseDomain/ClassMaker
   branch: master
  user: kyrillzotkin
  key:
    secure: V5PYXqvYP95mFxKw8eFqI9swYqdAgEg3AzyIxefjjBO+UGUjcKlw41R2qyYAlV+1Al9d6ZJ+nRLOE+v7yOUbC3+htGBaMdL22XE3te75aA5Sooc2VSEEDwtGtxdKKIUN2lgsPgKSff/DcOmWhLmpy56G3WMwq8S3cKrrrQnAE7oArljBL50OARJkY8Psdfy7PseJEptZ3Clm0geJjKTC2MGHaRBOKbCTBN2ZfbVGIKHN7jbDUN98glOmObIYnYMKEJsfhIBFP+Bxp+mTsGCntzZMNv5E4aghVC2N9yif4sLX/ZshSWSHkwkSdE42/ORfsH6KYsCegQD5frdDUAvib0nO/RiK0KfISNPJAl58Nnh1UvLVcPEVP5BQXJRfGfdrqjfZwCoUM5TI02lLaW1dykPZT4d6JbQ/3BG5FuAynU0IfgZDAFCDKjucowLy8np8nDO19dwqwB0Zu8uxg+4ke43oYU9AxuQAQ1yT2h+rSrquXB9WDcTLt8AxNsTELvs/Hqf6Fc8UQafBh4HY618dgaABxJKPCItpwXHrNTjd8PczQBv1URfU/2azg5urt2MBf0xW0ZE6lOPvWTadBjN9x/RORi9xh1THhPsA4bj0LP95dQ535EpaR4eoeQv4hjp6msfDq04oKA/sKYqrtXLG1f4NiMAB9BfnKAlV5dmvjLA=
  skip_cleanup: true
- provider: releases
  api_key:
    secure: p5pca9njDZoLAV7g69psgp3sDAEvY0mZTzStwnKVOWpSigG5N4wb8SuITmNa3NRF9P/uWfIAD23T43Jcxa72IH3FLCPZVZlIQDAHk+Qkk6QthjaUae/+aVMpaJ0EVR6OtimUD5ECi5aL+Qn8K8y7dFq1ZgOlYBovTK1TtPigsBnIDnOXO9Rr9IEDObsOZp03kCIUiy8YP9ir9K6dOWGmi2+fgPBM9CpowFVihEgc9/inwULf51lFzsg3iIxUpbxGAnIprUnBQd3uJag0a4YtImH/70x15cCsi01hgRfBh7Xba2FVfYVH/OncpzFAbQpUFka/k48fPYxoXFux3gpLCd0S9ZUgdF2RkDu48RQGQLdDw2V8mSSZ3W5Fds5V+p2QV2eB2dFmUhujLbsMOzx+5/+s2HIinOZh6nHDgfNWqQvRN3jXWiVHTvsL7TDjOitQCRMUyk2vic+3uHJRjPg+li1vFVlepCKyGRWT55vPP9UVtV1vsjD+nIFtkSQk/D+dcn6TMB4S/eA7cxEVafQtrUHhSDX+Mo/0zl8Di8aX6A8m5+J1CE7MX23cGvvXcyplWd53ihvIgZCZVV+u1dlnlkCLeuS7WHyKavqxDepC+d3GflLlclS78/bCaEwiXdXATYveORP3OKfhqEYRLQp0/ALKzQgE/p9xdiqtRq8j+PY=
  file:
  - releng/org.enterprisedomain.update/target/org.enterprisedomain.update-0.8.1-SNAPSHOT.zip
  - releng/org.enterprisedomain.workbench.ide.product/target/products/workbench-linux.gtk.x86_64.zip
  - releng/org.enterprisedomain.workbench.ide.product/target/products/workbench-macosx.cocoa.x86_64.zip
  - releng/org.enterprisedomain.workbench.ide.product/target/products/workbench-win32.win32.x86_64.zip
  on:
    repo: enterpriseDomain/ClassMaker
    tags: true        
  skip_cleanup: true

