<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="classsupplier" nsURI="http://org/classsupplier/0.7.2" nsPrefix="classsupplier">
  <eClassifiers xsi:type="ecore:EClass" name="Artifact">
    <eOperations name="make"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ePackage" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"
        changeable="false" volatile="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="prototypeEPackage" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="#//Version"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="#//State"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//IStatus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="loadedEPackage" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="State">
    <eLiterals name="CREATED"/>
    <eLiterals name="PROTOTYPE" value="1"/>
    <eLiterals name="PROCESSING" value="2"/>
    <eLiterals name="COMPLETE" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Infrastructure">
    <eOperations name="addRefreshListener">
      <eParameters name="listener" eType="#//Adapter"/>
    </eOperations>
    <eOperations name="removeRefreshListener">
      <eParameters name="listener" eType="#//Adapter"/>
    </eOperations>
    <eOperations name="createArtifact" eType="#//Artifact">
      <eParameters name="blueprint" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    </eOperations>
    <eOperations name="registerArtifact">
      <eParameters name="artifact" eType="#//Artifact"/>
    </eOperations>
    <eOperations name="unregisterArtifact">
      <eParameters name="artifact" eType="#//Artifact"/>
    </eOperations>
    <eOperations name="containsArtifact" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eParameters name="blueprint" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    </eOperations>
    <eOperations name="getArtifact" eType="#//Artifact">
      <eParameters name="projectName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getArtifact" eType="#//Artifact">
      <eParameters name="ePackage" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    </eOperations>
    <eOperations name="save"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="contents" upperBound="-1"
        eType="#//Artifact" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resourceSet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EResourceSet"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Adapter" instanceClassName="org.eclipse.emf.common.notify.Adapter"/>
  <eClassifiers xsi:type="ecore:EDataType" name="IStatus" instanceClassName="org.eclipse.core.runtime.IStatus"/>
  <eClassifiers xsi:type="ecore:EClass" name="ClassSupplier">
    <eOperations name="supply" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage">
      <eParameters name="model" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
    </eOperations>
    <eOperations name="supply" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage">
      <eParameters name="model" eType="ecore:EClass platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EPackage"/>
      <eParameters name="monitor" eType="#//IProgressMonitor"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workspace" eType="#//Infrastructure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="IProgressMonitor" instanceClassName="org.eclipse.core.runtime.IProgressMonitor"/>
  <eClassifiers xsi:type="ecore:EDataType" name="Version" instanceClassName="org.classsupplier.Version"/>
</ecore:EPackage>
