/**
 *
 * $Id$
 */
package org.enterprisedomain.classmaker.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.EObject;
import org.enterprisedomain.classmaker.CompletionListener;

/**
 * A sample validator interface for
 * {@link org.enterprisedomain.classmaker.Blueprint}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface BlueprintValidator {
	boolean validate();

	boolean validateDynamicModel(EObject value);

	boolean validateDependencies(EList<String> value);

	boolean validateCompletionListeners(EList<CompletionListener> value);

	boolean validateEdit(boolean value);

	boolean validateEditor(boolean value);
}
