/**
 *
 * $Id$
 */
package org.enterprisedomain.classmaker.validation;

import org.eclipse.core.runtime.IStatus;
import org.enterprisedomain.classmaker.Project;

/**
 * A sample validator interface for
 * {@link org.enterprisedomain.classmaker.CompletionNotificationAdapter}. This
 * doesn't really do anything, and it's not a real EMF artifact. It was
 * generated by the org.eclipse.emf.examples.generator.validator plug-in to
 * illustrate how EMF's code generator can be extended. This can be disabled
 * with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CompletionNotificationAdapterValidator {
	boolean validate();

	boolean validateError(IStatus value);

	boolean validateProject(Project value);
}
