/**
 *
 * $Id$
 */
package org.enterprisedomain.classmaker.validation;

import org.enterprisedomain.classmaker.State;

/**
 * A sample validator interface for {@link java.util.Map.Entry}. This doesn't
 * really do anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LongToStateMapEntryValidator {
	boolean validate();

	boolean validateTypedKey(Long value);

	boolean validateTypedValue(State value);
}
