/**
 *
 * $Id$
 */
package org.enterprisedomain.classmaker.validation;

import org.eclipse.emf.common.EMFPlugin;
import org.eclipse.emf.ecore.EObject;
import org.enterprisedomain.classmaker.Item;

/**
 * A sample validator interface for
 * {@link org.enterprisedomain.classmaker.Models}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ModelsValidator {
	boolean validate();

	boolean validateDynamic(EObject value);

	boolean validateGenerated(EObject value);

	boolean validateGeneratedEdit(EMFPlugin value);

	boolean validateGeneratedEditor(EMFPlugin value);

	boolean validateParent(Item value);
}
