/**
 *
 * $Id$
 */
package org.enterprisedomain.classmaker.validation;

import org.eclipse.emf.common.util.EList;
import org.enterprisedomain.classmaker.State;
import org.enterprisedomain.classmaker.jobs.Worker;

/**
 * A sample validator interface for
 * {@link org.enterprisedomain.classmaker.Strategy}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StrategyValidator {
	boolean validate();

	boolean validateGenerators(EList<Worker> value);

	boolean validateExporters(EList<Worker> value);

	boolean validateInstallers(EList<Worker> value);

	boolean validateLoaders(EList<Worker> value);

	boolean validateState(State value);
}
