/**
 *
 * $Id$
 */
package org.enterprisedomain.classmaker.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.enterprisedomain.classmaker.ClassMakerService;
import org.enterprisedomain.classmaker.Customizer;
import org.enterprisedomain.classmaker.Project;
import org.enterprisedomain.classmaker.SCMRegistry;
import org.enterprisedomain.classmaker.StageQualifier;

/**
 * A sample validator interface for
 * {@link org.enterprisedomain.classmaker.Workspace}. This doesn't really do
 * anything, and it's not a real EMF artifact. It was generated by the
 * org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's
 * code generator can be extended. This can be disabled with -vmargs
 * -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WorkspaceValidator {
	boolean validate();

	boolean validateProjects(EList<Project> value);

	boolean validateResourceSet(ResourceSet value);

	boolean validateCustomizers(EMap<StageQualifier, Customizer> value);

	boolean validateNonExclusiveCustomizers(EMap<StageQualifier, Customizer> value);

	boolean validateService(ClassMakerService value);

	boolean validateSCMRegistry(SCMRegistry<?> value);

	boolean validateExcludedEPackages(EList<EPackage> value);
}
