<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="imagesUI" nsURI="http://org/enterprisedomain/ClassMaker/Images/UI/1.0.0"
    nsPrefix="ImagesUI">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="basePackage" value="org.enterprisedomain.classmaker"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Measurement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="from" eType="#//Point"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="to" eType="#//Point"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Point" instanceClassName="org.eclipse.swt.graphics.Point"/>
</ecore:EPackage>
